apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-scraper-backend
  namespace: default
spec:
  replicas: 1  # You can change this to scale your app
  selector:
    matchLabels:
      app: web-scraper-backend
  template:
    metadata:
      labels:
        app: web-scraper-backend
    spec:
      containers:
      - name: web-scraper-backend
        imagePullPolicy: Always
        image: gcr.io/web-scraper-455220/web-scraper-backend:latest  # Ensure this points to the correct image tag
        ports:
          - containerPort: 5000
